name: aging_in_place
description: "A cross-platform app for tracking aging parents' ability to live at home."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^14.0.1

  # Native Features
  sign_in_with_apple: ^6.1.1
  share_plus: ^10.1.0
  path_provider: ^2.1.3
  pdf: ^3.11.1
  printing: ^5.13.1

  # Data Models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # Backend (Firebase)
  firebase_core: ^3.1.0
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.0
  
  # AI
  google_generative_ai: ^0.4.6 # For Gemini

  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1
  firebase_vertexai: ^1.8.3
  intl: ^0.20.2
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Code Generation
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "logos/favicon-512.png"
  image_path: "logos/favicon-512.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
